; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:gateway_base]
platform = espressif32
board = heltec_wifi_lora_32_V2
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
monitor_raw = true
build_unflags = 
	-std=gnu++11
build_flags = 
	-D LORAWAN_PREAMBLE_LENGTH=8
	-D MCU_ESP32_D0
	-D ARDUINO_HELTEC_WIFI_LORA_32_V2
	-D WIFI_LORA_32_V2
	-D HELTEC_WIFI_LORA_32_V2
	-D REGION_AU915
	-D LORA_DISPLAY
	-D HELTEC_BOARD=0
	-D RADIO_CHIP_SX127X
	-D SLOW_CLK_TYPE=0
	-DCONFIG_LITTLEFS_FOR_IDF_3_2
	-Wall
	-Wextra
	-Wshadow
	-Wconversion
	-Wpedantic
	-std=gnu++2a
check_tool = clangtidy, cppcheck
check_flags =
	clangtidy: --config-file=.clang-tidy
	cppcheck: --enable=warning,style,performance,portability
extra_scripts =
	pre:scripts/check_architecture.py
lib_deps = 
	Wire
	WiFi
	SPI
	Preferences
	littlefs
	WebServer

[env:without_wifi]
extends = env:gateway_base
build_flags = 
	${env:gateway_base.build_flags}
	-D FW_VERBOSE=0
	-D LoRaWAN_DEBUG_LEVEL=0

[env:with_fake_wifi]
extends = env:gateway_base
debug_build_flags = -O0 -ggdb3 -g3
build_flags = 
	${env:gateway_base.build_flags}
	-D DEBUG
	-DFAKER
	-D FW_VERBOSE=1
	-D LoRaWAN_DEBUG_LEVEL=3
lib_deps = 
	${env:gateway_base.lib_deps}
